// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migraiton_message_rename_content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migraiton_message_rename_content));
        
        string IMigrationMetadata.Id
        {
            get { return "202207160126123_migraiton_message_rename_content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
